// <auto-generated />
namespace DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Update09 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update09));
        
        string IMigrationMetadata.Id
        {
            get { return "201501300933438_Update09"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
