DELETE FROM STATO WHERE ENTITAASSOCIATA = 3
DELETE FROM STATO WHERE ENTITAASSOCIATA = 4
DELETE FROM STATO WHERE DESCRIZIONE = 'ATTIVA' AND  ENTITAASSOCIATA = 2
DELETE FROM STATO WHERE DESCRIZIONE = 'DISATTIVA' AND  ENTITAASSOCIATA = 2
DELETE FROM STATO WHERE DESCRIZIONE = 'DISATTIVA' AND  ENTITAASSOCIATA = 2
GO
INSERT INTO PROFILO ( profilo_id, nome, date_added) VALUES ( 'TEMP', 'TEMP', GetDate());
GO
UPDATE UtenteProfilo SET PROFILO_ID = 'TEMP' WHERE PROFILO_ID = 'ADMIN'
UPDATE PROFILO SET PROFILO_ID = 'AMMINISTRATORE' WHERE PROFILO_ID = 'ADMIN'
UPDATE UtenteProfilo SET PROFILO_ID = 'AMMINISTRATORE' WHERE PROFILO_ID = 'TEMP'
GO
UPDATE UtenteProfilo SET PROFILO_ID = 'TEMP' WHERE PROFILO_ID = 'BACKOFFICE'
UPDATE UtenteProfilo SET PROFILO_ID = 'TEMP' WHERE PROFILO_ID = 'FRONTOFFICE'
UPDATE PROFILO SET PROFILO_ID = 'DIPENDENTE', nome = 'Dipendente' WHERE PROFILO_ID = 'BACKOFFICE'
DELETE PROFILO WHERE PROFILO_ID = 'FRONTOFFICE'
UPDATE UtenteProfilo SET PROFILO_ID = 'DIPENDENTE' WHERE PROFILO_ID = 'TEMP'
GO
DELETE PROFILO WHERE PROFILO_ID = 'TEMP'
GO
